// SPDX-FileCopyrightText: 2026 ThinkHome s.r.o.
// SPDX-License-Identifier: MPL-2.0

export { createIsdsClient, type CreateIsdsClientOptions, type IsdsClient } from "./client/index.ts";
export { resolveEnvironment, type IsdsEnvironment, type IsdsEndpointMap } from "./config/environment.ts";
export { type IsdsAuthentication, PasswordAuthAdapter } from "./auth/index.ts";
export { type IsdsCapabilities } from "./capabilities/index.ts";
export {
  DataBoxesClient,
  type ActivityPeriod,
  type ActivityStatusResult,
  type ChangePasswordResult,
  type ConstantRecord,
  type ConstantsResult,
  type CreditInfoOptions,
  type CreditInfoResult,
  type CreditRecord,
  type DataBoxAddressResult,
  type DataBoxCheckResult,
  type DataBoxListResult,
  type DataBoxOwnerInfo,
  type DataBoxOwnerResult,
  type DataBoxUserInfo,
  type DataBoxUserResult,
  type DbStatusResult,
  type DtInfoResult,
  type FindDataBoxesOptions,
  type FindDataBoxesResult,
  type IsdsSearchOptions,
  type IsdsSearchRecord,
  type IsdsSearchResult,
  type PasswordInfoResult,
  type PdzInfoResult,
  type PdzRecord,
  type PdzSendInfoResult,
} from "./data-boxes/index.ts";
export {
  MessagesClient,
  type AuthenticateMessageResult,
  type CreateMessageEnvelopeOptions,
  type CreateMessageFile,
  type CreateMessageFileMetaType,
  type CreateMessageOptions,
  type CreateMessageResult,
  type CreateMultipleMessageRecipient,
  type CreateMultipleMessageStatus,
  type CreateMultipleMessagesOptions,
  type CreateMultipleMessagesResult,
  type ListReceivedMessagesOptions,
  type ListReceivedMessagesResult,
  type ListSentMessagesOptions,
  type ListSentMessagesResult,
  type DeliveryEvent,
  type DeliveryInfoResult,
  type DownloadedMessageFile,
  type EraseMessageOptions,
  type EraseMessageResult,
  type GetErasedMessagesListOptions,
  type GetErasedMessagesListResult,
  type GetMessageStateChangesOptions,
  type GetMessageStateChangesResult,
  type GetNotificationsOptions,
  type GetNotificationsResult,
  type MarkMessageAsDownloadedResult,
  type MessageHash,
  type MessageAuthorResult,
  type MessageDownloadResult,
  type MessageEnvelopeDownloadResult,
  type MessageStateChange,
  type NotificationRecord,
  type PickUpAsyncResponseResult,
  type ReceivedMessageRecord,
  type RegisterForNotificationsOptions,
  type RegisterForNotificationsResult,
  type ReportSuspiciousMessageOptions,
  type ReportSuspiciousMessageResult,
  type ReSignISDSDocumentResult,
  type SentMessageEnvelopeDownloadResult,
  type SignedDeliveryInfoResult,
  type SignedMessageDownloadResult,
  type SentMessageRecord,
  type StatusOnlyResult,
  type VerifyMessageResult,
} from "./messages/index.ts";
export * from "./xml/index.ts";
export * from "./soap/index.ts";
export * from "./mtom/index.ts";
export * from "./errors/index.ts";
