// SPDX-FileCopyrightText: 2026 ThinkHome s.r.o.
// SPDX-License-Identifier: MPL-2.0

import type { RawOperationMetadata } from "./index.ts";

export const GENERATED_OPERATIONS = [
  {
    "operation": "GetOwnerInfoFromLogin",
    "service": "DataBoxAccess",
    "port": "DataBoxAccessPortType",
    "binding": "DataBoxAccessBinding",
    "endpointCategory": "info",
    "endpoint": "https://ws1.datovka.gov.cz/DS/DsManage",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetOwnerInfoFromLoginRequest",
    "responseMessage": "GetOwnerInfoFromLoginResponse",
    "sourceWsdl": "db_access.wsdl",
    "sourceWsdlSha256": "c655b2e1cbe6b4f81ac707f9fac555fe056d2e91a81de71e305e320de99569ea"
  },
  {
    "operation": "GetOwnerInfoFromLogin2",
    "service": "DataBoxAccess",
    "port": "DataBoxAccessPortType",
    "binding": "DataBoxAccessBinding",
    "endpointCategory": "info",
    "endpoint": "https://ws1.datovka.gov.cz/DS/DsManage",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetOwnerInfoFromLogin2Request",
    "responseMessage": "GetOwnerInfoFromLogin2Response",
    "sourceWsdl": "db_access.wsdl",
    "sourceWsdlSha256": "c655b2e1cbe6b4f81ac707f9fac555fe056d2e91a81de71e305e320de99569ea"
  },
  {
    "operation": "GetUserInfoFromLogin",
    "service": "DataBoxAccess",
    "port": "DataBoxAccessPortType",
    "binding": "DataBoxAccessBinding",
    "endpointCategory": "info",
    "endpoint": "https://ws1.datovka.gov.cz/DS/DsManage",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetUserInfoFromLoginRequest",
    "responseMessage": "GetUserInfoFromLoginResponse",
    "sourceWsdl": "db_access.wsdl",
    "sourceWsdlSha256": "c655b2e1cbe6b4f81ac707f9fac555fe056d2e91a81de71e305e320de99569ea"
  },
  {
    "operation": "GetUserInfoFromLogin2",
    "service": "DataBoxAccess",
    "port": "DataBoxAccessPortType",
    "binding": "DataBoxAccessBinding",
    "endpointCategory": "info",
    "endpoint": "https://ws1.datovka.gov.cz/DS/DsManage",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetUserInfoFromLogin2Request",
    "responseMessage": "GetUserInfoFromLogin2Response",
    "sourceWsdl": "db_access.wsdl",
    "sourceWsdlSha256": "c655b2e1cbe6b4f81ac707f9fac555fe056d2e91a81de71e305e320de99569ea"
  },
  {
    "operation": "ChangeISDSPassword",
    "service": "DataBoxAccess",
    "port": "DataBoxAccessPortType",
    "binding": "DataBoxAccessBinding",
    "endpointCategory": "info",
    "endpoint": "https://ws1.datovka.gov.cz/DS/DsManage",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "ChangeISDSPasswordRequest",
    "responseMessage": "ChangeISDSPasswordResponse",
    "sourceWsdl": "db_access.wsdl",
    "sourceWsdlSha256": "c655b2e1cbe6b4f81ac707f9fac555fe056d2e91a81de71e305e320de99569ea"
  },
  {
    "operation": "GetPasswordInfo",
    "service": "DataBoxAccess",
    "port": "DataBoxAccessPortType",
    "binding": "DataBoxAccessBinding",
    "endpointCategory": "info",
    "endpoint": "https://ws1.datovka.gov.cz/DS/DsManage",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetPasswordInfoRequest",
    "responseMessage": "GetPasswordInfoResponse",
    "sourceWsdl": "db_access.wsdl",
    "sourceWsdlSha256": "c655b2e1cbe6b4f81ac707f9fac555fe056d2e91a81de71e305e320de99569ea"
  },
  {
    "operation": "FindDataBox",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "FindDataBoxRequest",
    "responseMessage": "FindDataBoxResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "FindDataBox2",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "FindDataBox2Request",
    "responseMessage": "FindDataBox2Response",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "CheckDataBox",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "CheckDataBoxRequest",
    "responseMessage": "CheckDataBoxResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "GetDataBoxList",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetDataBoxListRequest",
    "responseMessage": "GetDataBoxListResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "PDZInfo",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "PDZInfoRequest",
    "responseMessage": "PDZInfoResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "DataBoxCreditInfo",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "DataBoxCreditInfoRequest",
    "responseMessage": "DataBoxCreditInfoResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "ISDSSearch2",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "ISDSSearch2Request",
    "responseMessage": "ISDSSearch2Response",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "ISDSSearch3",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "ISDSSearch3Request",
    "responseMessage": "ISDSSearch3Response",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "GetDataBoxActivityStatus",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetDataBoxActivityStatusRequest",
    "responseMessage": "GetDataBoxActivityStatusResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "FindPersonalDataBox",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "FindPersonalDataBoxRequest",
    "responseMessage": "FindPersonalDataBoxResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "DTInfo",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "DTInfoRequest",
    "responseMessage": "DTInfoResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "PDZSendInfo",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "PDZSendInfoRequest",
    "responseMessage": "PDZSendInfoResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "GetConstants",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetConstantsRequest",
    "responseMessage": "GetConstantsResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "GetDataBoxAddress",
    "service": "DataBoxSearch",
    "port": "DataBoxSearchPortType",
    "binding": "DataBoxSearchBinding",
    "endpointCategory": "search",
    "endpoint": "https://ws1.datovka.gov.cz/DS/df",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetDataBoxAddressRequest",
    "responseMessage": "GetDataBoxAddressResponse",
    "sourceWsdl": "db_search.wsdl",
    "sourceWsdlSha256": "e4540467025adbdf097803e741dc604eaef24fdf26ce7d38e4f5f590b2f53670"
  },
  {
    "operation": "VerifyMessage",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "MessageVerifyRequest",
    "responseMessage": "MessageVerifyResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "MessageEnvelopeDownload",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "MessageEnvelopeDownloadRequest",
    "responseMessage": "MessageEnvelopeDownloadResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "MarkMessageAsDownloaded",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "MarkMessageAsDownloadedRequest",
    "responseMessage": "MarkMessageAsDownloadedResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetDeliveryInfo",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "DeliveryMessageRequest",
    "responseMessage": "DeliveryMessageResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetSignedDeliveryInfo",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "SignedDeliveryMessageRequest",
    "responseMessage": "SignedDeliveryMessageResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetListOfSentMessages",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "ListOfSentMessagesRequest",
    "responseMessage": "ListOfSentMessagesResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetListOfReceivedMessages",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "ListOfReceivedMessagesRequest",
    "responseMessage": "ListOfReceivedMessagesResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetMessageStateChanges",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetMessageStateChangesRequest",
    "responseMessage": "GetMessageStateChangesResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetMessageAuthor",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetMessageAuthorRequest",
    "responseMessage": "GetMessageAuthorResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetMessageAuthor2",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetMessageAuthor2Request",
    "responseMessage": "GetMessageAuthor2Response",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "EraseMessage",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "EraseMessageRequest",
    "responseMessage": "EraseMessageResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetListOfErasedMessages",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetListOfErasedMessagesRequest",
    "responseMessage": "GetListOfErasedMessagesResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "PickUpAsyncResponse",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "PickUpAsyncResponseRequest",
    "responseMessage": "PickUpAsyncResponseResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "GetListForNotifications",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "GetListForNotificationsRequest",
    "responseMessage": "GetListForNotificationsResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "RegisterForNotifications",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "RegisterForNotificationsRequest",
    "responseMessage": "RegisterForNotificationsResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "SentMessageEnvelopeDownload",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "SentMessageEnvelopeDownloadRequest",
    "responseMessage": "SentMessageEnvelopeDownloadResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "SuspMessageReport",
    "service": "dmInfoWebService",
    "port": "dmInfoPortType",
    "binding": "dmInfoBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dx",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "SuspMessageReportRequest",
    "responseMessage": "SuspMessageReportResponse",
    "sourceWsdl": "dm_info.wsdl",
    "sourceWsdlSha256": "b82c99e6cfbd80bdbdb20825cfdfba0a47d0894c4369a7f6708115984db8b5ac"
  },
  {
    "operation": "CreateMessage",
    "service": "dmOperationsWebService",
    "port": "dmOperationsPortType",
    "binding": "dmOperationsBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dz",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "MessageCreateRequest",
    "responseMessage": "MessageCreateResponse",
    "sourceWsdl": "dm_operations.wsdl",
    "sourceWsdlSha256": "80c3ed286c5c2775be8db64813c41ec54509b94d3839132192b03a65589bf905"
  },
  {
    "operation": "MessageDownload",
    "service": "dmOperationsWebService",
    "port": "dmOperationsPortType",
    "binding": "dmOperationsBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dz",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "MessageDownloadRequest",
    "responseMessage": "MessageDownloadResponse",
    "sourceWsdl": "dm_operations.wsdl",
    "sourceWsdlSha256": "80c3ed286c5c2775be8db64813c41ec54509b94d3839132192b03a65589bf905"
  },
  {
    "operation": "SignedMessageDownload",
    "service": "dmOperationsWebService",
    "port": "dmOperationsPortType",
    "binding": "dmOperationsBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dz",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "SignedMessageDownloadRequest",
    "responseMessage": "SignedMessageDownloadResponse",
    "sourceWsdl": "dm_operations.wsdl",
    "sourceWsdlSha256": "80c3ed286c5c2775be8db64813c41ec54509b94d3839132192b03a65589bf905"
  },
  {
    "operation": "SignedSentMessageDownload",
    "service": "dmOperationsWebService",
    "port": "dmOperationsPortType",
    "binding": "dmOperationsBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dz",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "SignedSentMessageDownloadRequest",
    "responseMessage": "SignedSentMessageDownloadResponse",
    "sourceWsdl": "dm_operations.wsdl",
    "sourceWsdlSha256": "80c3ed286c5c2775be8db64813c41ec54509b94d3839132192b03a65589bf905"
  },
  {
    "operation": "DummyOperation",
    "service": "dmOperationsWebService",
    "port": "dmOperationsPortType",
    "binding": "dmOperationsBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dz",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "DummyOperationRequest",
    "responseMessage": "DummyOperationResponse",
    "sourceWsdl": "dm_operations.wsdl",
    "sourceWsdlSha256": "80c3ed286c5c2775be8db64813c41ec54509b94d3839132192b03a65589bf905"
  },
  {
    "operation": "CreateMultipleMessage",
    "service": "dmOperationsWebService",
    "port": "dmOperationsPortType",
    "binding": "dmOperationsBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dz",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "MultipleMessageCreateRequest",
    "responseMessage": "MultipleMessageCreateResponse",
    "sourceWsdl": "dm_operations.wsdl",
    "sourceWsdlSha256": "80c3ed286c5c2775be8db64813c41ec54509b94d3839132192b03a65589bf905"
  },
  {
    "operation": "AuthenticateMessage",
    "service": "dmOperationsWebService",
    "port": "dmOperationsPortType",
    "binding": "dmOperationsBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dz",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": true,
    "requestMessage": "AuthenticateMessageRequest",
    "responseMessage": "AuthenticateMessageResponse",
    "sourceWsdl": "dm_operations.wsdl",
    "sourceWsdlSha256": "80c3ed286c5c2775be8db64813c41ec54509b94d3839132192b03a65589bf905"
  },
  {
    "operation": "Re-signISDSDocument",
    "service": "dmOperationsWebService",
    "port": "dmOperationsPortType",
    "binding": "dmOperationsBinding",
    "endpointCategory": "messages",
    "endpoint": "https://ws1.datovka.gov.cz/DS/dz",
    "soapAction": "",
    "soapVersion": "1.1",
    "idempotent": false,
    "requestMessage": "Re-signISDSDocumentRequest",
    "responseMessage": "Re-signISDSDocumentResponse",
    "sourceWsdl": "dm_operations.wsdl",
    "sourceWsdlSha256": "80c3ed286c5c2775be8db64813c41ec54509b94d3839132192b03a65589bf905"
  }
] as const satisfies readonly RawOperationMetadata[];
